name: build docker
on: [push]
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_blocknetdximg_password }} | docker login --username ${{ secrets.org_blocknetdximg_username }} --password-stdin

    # Build images
    - name: INFO BUILD
      run: echo ${{ github.event.inputs.path }} ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: build an image
      if: github.ref == 'refs/heads/master'
      run: docker build ./event-processor/ --file Dockerfile --tag blocknetdx/xquery-event-processor:latest
    - name: push image
      if: github.ref == 'refs/heads/master'
      run: docker push blocknetdx/xquery-event-processor:latest
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
